# Project7 
### 3 bit/4 bit/5 bit LSB
### caculate each bit of PSNR

In [1]:
import math

def decimalToBinaryCode(num:int):
    divisor=0
    arrList=list()
    arrList.clear()

    dividend=num
    ## 沒有寫floor會出錯
    while(dividend/2!=0):
            divisor+=1
            dividend=math.floor(dividend/2)
    ## end while

    while(divisor>=0):
        if(num>=math.pow(2,divisor)):
                num-=math.pow(2,divisor)
                divisor-=1
                arrList.append('1')
        else:
                divisor-=1
                arrList.append('0')
            ##end if-else
    ## end while


    while(len(arrList)<8):
        arrList.insert(0,0)
    ## end while

    binary_string: str = ""
    for char_num in arrList:
        binary_string = binary_string + str(char_num)
    
    return binary_string
##end define

In [2]:
def binaryToDecimal(string:str):
    num=int(string)
    dec:int=0
    for i in range (len(string)):
        if((num%10)==1):
            dec+=math.pow(2,i)
        
        num=int(num/10)
    #end for
    return dec 

##### readIMGpixel

In [3]:
from PIL import Image
import numpy as np

def readIMGtopixel(path):
    WIDTH=int(0)
    HEIGHT=int(0)
    img: Image =Image.open(path)
    imgMatrix = np.array(Image.open(path).convert('L'),'i') #dtype=int
    HEIGHT=int(img.height)
    WIDTH=int(img.width)
    return imgMatrix,HEIGHT,WIDTH
#end def

In [4]:
def readTextFile(path):
    with open(path,'r') as f:
        text=f.read()

    return text

In [5]:
def writeTextFile(path,string):
    with open(path,'w') as f:
        f.write(string)
    

#### Main

In [6]:
# read original text and bmp file
originalText=readTextFile("./../Txt_File .txt")
originalIMG,HEIGHT,WIDTH=readIMGtopixel("./../Img_File.bmp")

In [7]:
#convert text to 7 bit binary code
textToBin=""
for element in originalText:
    #temp would be 8 bit from decimalToBinaryCode
    temp:str=decimalToBinaryCode(ord(element))
    textToBin+=temp[1:]


In [8]:
writeTextFile("./textConvertTo7bitBin.txt",textToBin)

In [9]:
def splitTxtByBit(BITLENTH:int,originalBinary:str):
    binary=originalBinary
    bitList=[]
    while(len(binary)>BITLENTH):
        temp=binary[0:BITLENTH]
        bitList.append(temp)
        binary=binary[BITLENTH:]

    #when the last less than BITLENTH
    while(len(binary)<BITLENTH):
        binary+="0"

    #append last to List 
    bitList.append(binary)
    #append 0 to mark file end
    zeroString:str=""
    while(len(zeroString)<BITLENTH):
        zeroString+="0"

    bitList.append(zeroString)
    bitList.append(zeroString)
    bitList.append(zeroString)

    return bitList

In [10]:
threeBitList=splitTxtByBit(3,textToBin)
fourBitList=splitTxtByBit(4,textToBin)
fiveBitList=splitTxtByBit(5,textToBin)

In [11]:
#convert original pixcel value from decimal to binary
imgBin=np.zeros(originalIMG.shape,dtype=int)
for i_vertical in range(HEIGHT):
    for i_horizontal in range(WIDTH):
        imgBin[i_vertical][i_horizontal]=decimalToBinaryCode(int(originalIMG[i_vertical][i_horizontal]))

print(imgBin)

[[10011111 10011111 10011110 ... 10100111 10011000 10000000]
 [10100000 10011110 10011110 ... 10100110 10011001 10000000]
 [10011111 10011111 10011111 ... 10100110 10011001 10000001]
 ...
 [  110101   110100   111100 ...  1101011  1101011  1101111]
 [  110100   110101   111101 ...  1101010  1101101  1101111]
 [ 1111011  1111110 10000100 ...  1111101  1110010  1011101]]


In [12]:
#remove last three bit and add information
cnt:int = 0
threebit_img=imgBin.copy()
for i_vertical in range(HEIGHT):
    for i_horizontal in range(WIDTH):
        tempString=threebit_img[i_vertical][i_horizontal]# get pixcel's 8 bit binary code
        tempString=str(tempString) #change its dtype from int32 to string
        tempString=tempString[:-3]+str(threeBitList[cnt]) # discard last 3 bit of pixcel and combine 3 bit from text file
        tempString=int(tempString) #change dtype of combined string from string to int
        cnt+=1
        threebit_img[i_vertical][i_horizontal]=tempString # store result
        if(cnt==len(threeBitList)-1):
            cnt=0
    if(cnt==len(threeBitList)-1):
        cnt=0

print(threebit_img)

[[10011101 10011010 10011011 ... 10100101 10011001 10000110]
 [10100111 10011011 10011000 ... 10100110 10011010 10000000]
 [10011011 10011100 10011111 ... 10100110 10011111 10000001]
 ...
 [  110110   110100   111110 ...  1101010  1101001  1101100]
 [  110101   110010   111000 ...  1101011  1101110  1101011]
 [ 1111111  1111010 10000011 ...  1111101  1110001  1011110]]


In [13]:
#remove last four bit and add information
cnt:int = 0
fourbit_img=imgBin.copy()
for i_vertical in range(HEIGHT):
    for i_horizontal in range(WIDTH):
        tempString=fourbit_img[i_vertical][i_horizontal]# get pixcel's 8 bit binary code
        tempString=str(tempString) #change its dtype from int32 to string
        tempString=tempString[:-4]+str(fourBitList[cnt]) # discard last 3 bit of pixcel and combine 3 bit from text file
        tempString=int(tempString) #change dtype of combined string from string to int
        cnt+=1
        fourbit_img[i_vertical][i_horizontal]=tempString # store result
        if(cnt==len(fourBitList)-1):
            cnt=0
    if(cnt==len(fourBitList)-1):
        cnt=0

print(fourbit_img)

[[10011010 10011001 10011010 ... 10100110 10011000 10001100]
 [10101010 10011000 10010011 ... 10100010 10011110 10001000]
 [10011000 10010010 10011001 ... 10100101 10011000 10001000]
 ...
 [  110000   111110   111001 ...  1101000  1100010  1101010]
 [  111110   111110   111101 ...  1100001  1101011  1101011]
 [ 1110101  1110110 10000000 ...  1110110  1110010  1010000]]


In [14]:
#remove last five bit and add information
cnt:int = 0
fivebit_img=imgBin.copy()
for i_vertical in range(HEIGHT):
    for i_horizontal in range(WIDTH):
        tempString=fourbit_img[i_vertical][i_horizontal]# get pixcel's 8 bit binary code
        tempString=str(tempString) #change its dtype from int32 to string
        tempString=tempString[:-5]+str(fiveBitList[cnt]) # discard last 3 bit of pixcel and combine 3 bit from text file
        tempString=int(tempString) #change dtype of combined string from string to int
        cnt+=1
        fivebit_img[i_vertical][i_horizontal]=tempString # store result
        if(cnt==len(fiveBitList)-1):
            cnt=0
    if(cnt==len(fiveBitList)-1):
        cnt=0

print(fivebit_img)


[[10010101 10000110 10010001 ... 10110111 10010010 10001000]
 [10100011 10000010 10011100 ... 10101110 10011001 10011010]
 [10000001 10011010 10001110 ... 10111010 10001110 10011000]
 ...
 [  111001   101110   100011 ...  1111010  1101110  1111111]
 [  110111   100100   100011 ...  1100111  1100101  1111100]
 [ 1110100  1100011 10010100 ...  1101011  1111001  1010100]]


#### convert pixcel from binary to decimal

In [15]:
for i_vertical in range(HEIGHT):
    for i_horizontal in range(WIDTH):
        threebit_img[i_vertical][i_horizontal]=binaryToDecimal(str(threebit_img[i_vertical][i_horizontal]))

print(threebit_img)
for i_vertical in range(HEIGHT):
    for i_horizontal in range(WIDTH):
        fourbit_img[i_vertical][i_horizontal]=binaryToDecimal(str(fourbit_img[i_vertical][i_horizontal]))

print(fourbit_img)
for i_vertical in range(HEIGHT):
    for i_horizontal in range(WIDTH):
        fivebit_img[i_vertical][i_horizontal]=binaryToDecimal(str(fivebit_img[i_vertical][i_horizontal]))

print(fivebit_img)

[[157 154 155 ... 165 153 134]
 [167 155 152 ... 166 154 128]
 [155 156 159 ... 166 159 129]
 ...
 [ 54  52  62 ... 106 105 108]
 [ 53  50  56 ... 107 110 107]
 [127 122 131 ... 125 113  94]]
[[154 153 154 ... 166 152 140]
 [170 152 147 ... 162 158 136]
 [152 146 153 ... 165 152 136]
 ...
 [ 48  62  57 ... 104  98 106]
 [ 62  62  61 ...  97 107 107]
 [117 118 128 ... 118 114  80]]
[[149 134 145 ... 183 146 136]
 [163 130 156 ... 174 153 154]
 [129 154 142 ... 186 142 152]
 ...
 [ 57  46  35 ... 122 110 127]
 [ 55  36  35 ... 103 101 124]
 [116  99 148 ... 107 121  84]]


#### 寫成圖檔

In [16]:
output3Bit=Image.fromarray(threebit_img)
output3Bit=output3Bit.convert('L')
output3Bit.save(".\output3bit.bmp")
output3Bit.show()

output4Bit=Image.fromarray(fourbit_img)
output4Bit=output4Bit.convert('L')
output4Bit.save(".\output4bit.bmp")
output4Bit.show()

output5Bit=Image.fromarray(fivebit_img)
output5Bit=output5Bit.convert('L')
output5Bit.save(".\output5bit.bmp")
output5Bit.show()

## PSNR


In [17]:
#caculate MSE
MSE3:int=0
MSE4:int=0
MSE5:int=0
for i in range(HEIGHT):
    for j in range(WIDTH):
        MSE3+=(originalIMG[i][j]-threebit_img[i][j])**2
        MSE4+=(originalIMG[i][j]-fourbit_img[i][j])**2
        MSE5+=(originalIMG[i][j]-fivebit_img[i][j])**2

MSE3=MSE3/(512**2)
MSE4=MSE4/(512**2)
MSE5=MSE5/(512**2)
print("MSE3 : "+str(MSE3))
print("MSE4 : "+str(MSE4))
print("MSE5 : "+str(MSE5))

MSE3 : 10.587913513183594
MSE4 : 42.52855682373047
MSE5 : 173.88193130493164


In [18]:
#caculate PSNR
# the bigger the value of PSNR is, the more loss of image is. 
PSNR3:int=0.0
PSNR4:int=0.0
PSNR5:int=0.0
PSNR3=10*math.log(512*512/MSE3,10)
PSNR4=10*math.log(512*512/MSE4,10)
PSNR5=10*math.log(512*512/MSE5,10)
print("PSNR of 3 bit bmp file is "+str(PSNR3)+" dB")
print("PSNR of 4 bit bmp file is "+str(PSNR4)+" dB")
print("PSNR of 5 bit bmp file is "+str(PSNR5)+" dB")

PSNR of 3 bit bmp file is 43.93729536819567 dB
PSNR of 4 bit bmp file is 37.89859276461351 dB
PSNR of 5 bit bmp file is 31.782854667014572 dB
