### 將十進制轉成二進制函式
###### 輸入int 輸出 string

In [1]:
import math

def decimalToBinary(num:int):
    divisor=0
    arrList=list()
    arrList.clear()

    dividend=num
    ## 沒有寫floor會出錯
    while(dividend/2!=0):
            divisor+=1
            dividend=math.floor(dividend/2)
    ## end while

    while(divisor>=0):
        if(num>=math.pow(2,divisor)):
                num-=math.pow(2,divisor)
                divisor-=1
                arrList.append('1')
        else:
                divisor-=1
                arrList.append('0')
            ##end if-else
    ## end while


    while(len(arrList)<8):
        arrList.insert(0,0)
    ## end while

    binary_string: str = ""
    for char_num in arrList:
        binary_string = binary_string + str(char_num)

    # str: str="".join(arrList)
    # if __name__=='_main_':
    #     return str
    
    return binary_string
##end define

In [2]:
from PIL import Image
import numpy as np

WIDTH=int(0)
HEIGHT=int(0)
def readIMGtopixel(path):
    img: Image =Image.open(path)
    imgMatrix = np.array(Image.open(path).convert('L'),'i') #dtype=int
    HEIGHT=int(img.height)
    WIDTH=int(img.width)
    return imgMatrix
#end def

In [3]:
img=readIMGtopixel("Img_File.bmp") #img : matrix
print(img)

[[159 159 158 ... 167 152 128]
 [160 158 158 ... 166 153 128]
 [159 159 159 ... 166 153 129]
 ...
 [ 53  52  60 ... 107 107 111]
 [ 52  53  61 ... 106 109 111]
 [123 126 132 ... 125 114  93]]


In [4]:
width,height=img.shape
binMatrix=np.zeros((width,height),dtype=int)
for i_vertical in range(height):
    for i_horizen in range (width):
        temp=decimalToBinary(img[i_vertical][i_horizen])
        binMatrix[i_vertical][i_horizen]=temp
#end for

print(binMatrix)
        

[[10011111 10011111 10011110 ... 10100111 10011000 10000000]
 [10100000 10011110 10011110 ... 10100110 10011001 10000000]
 [10011111 10011111 10011111 ... 10100110 10011001 10000001]
 ...
 [  110101   110100   111100 ...  1101011  1101011  1101111]
 [  110100   110101   111101 ...  1101010  1101101  1101111]
 [ 1111011  1111110 10000100 ...  1111101  1110010  1011101]]


In [32]:
def binaryToDecimal(num):
    temp=num
    dec=int(0)
    for i in range (len(str(num))):
        if((temp%10)==1):
            dec+=math.pow(2,i)
        
        temp=int(temp/10)
    #end for
    return dec;

In [33]:
convertBackMatrix=np.zeros((width,height),dtype=int)
for i_vertical in range(height):
    for i_horizen in range (width):
        convertBackMatrix[i_vertical][i_horizen]=binaryToDecimal(binMatrix[i_vertical][i_horizen])
#end for
print(convertBackMatrix)

[[159 159 158 ... 167 152 128]
 [160 158 158 ... 166 153 128]
 [159 159 159 ... 166 153 129]
 ...
 [ 53  52  60 ... 107 107 111]
 [ 52  53  61 ... 106 109 111]
 [123 126 132 ... 125 114  93]]


# 嘗試將矩陣轉成圖檔

In [35]:
converBackIMG=Image.fromarray(convertBackMatrix)
converBackIMG.show()